version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: museum-locator:latest
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - museumdb
    env_file:
      - .env

  museumdb:
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 15s
      retries: 5
    container_name: museumdb
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
